config/routes.rb
Rails.application.routes.draw do

  # Vistas para el divisional

  # get '/altas', to: 'managers#altas', as: 'altas'
  # get '/bajas', to: 'managers#bajas', as: 'bajas'
  get '/dotaciones', to: 'managers#dotaciones', as: 'dotaciones'
  get '/manager', to: 'managers#dotaciones', as: 'manager'
  get '/movimientos', to: 'managers#movimientos', as: 'movimientos'
  get '/formaciones', to: 'managers#formaciones', as: 'formaciones'
  get '/rotaciones', to: 'managers#rotaciones', as: 'rotaciones'
  get '/remuneraciones', to: 'managers#remuneraciones', as: 'remuneraciones'
  get '/vacaciones', to: 'managers#vacaciones', as: 'vacaciones'
  get '/saldo-vacaciones', to: 'managers#saldo', as: 'saldo'
  # get '/personas', to: 'managers#personas', as: 'personas'
  get '/licencias', to: 'managers#licencias', as: 'licencias'
  #post '/entrada', to: 'managers#entrada', as: 'entrada'
  
  devise_scope :user do
    get 'login', to: 'users/sessions#create'
  end
  get '/users/entrada', to: 'managers#entrada', as: 'user_with_params'
  # post '/users/entrada', to: 'managers#entrada', as: 'user_with_params'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'managers#index'

  namespace :admin do
    post ':model_type/upload', to: 'upload#create', as: :upload
    post ':model_type/remove', to: 'upload#remove', as: :remove
    post '/generate', to: 'upload#generate', as: :generate
    get '/ordenar_gerencias', to: 'vacantes#ordenar_gerencias', as: :ordenar_gerencias
    get '/ordenar_divisiones', to: 'vacantes#ordenar_divisiones', as: :ordenar_divisiones
    post '/crear_orden_gerencias', to: 'vacantes#crear_orden_gerencias', as: :crear_orden_gerencias
    post '/crear_orden_divisiones', to: 'vacantes#crear_orden_divisiones', as: :crear_orden_divisiones
    get '/user/:id/log', to: 'users#log', as: :log_user
    resources :formaciones
    resources :licencias
    resources :empleados
    resources :users
    resources :movimientos
    resources :egresos
    resources :posiciones
    resources :retribuciones
    resources :vacaciones
    resources :vacantes
    resources :user_logs

    root "empleados#index", as: :home
  end

  post "update_role" => "roles#update", as: "update_role"
  resources :users do
    get 'resend_invite', to: "users#resend_invite", as: "resend_invite"
  end

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post 'upload' => 'upload#create'
      get 'remove' => 'upload#remove'
      get 'generate' => 'upload#generate'
      get 'programa-talentos' => 'programa_talentos#index'
      get 'programa-talentos/:id' => 'programa_talentos#show'
      post 'programa-talentos' => 'programa_talentos#create'
      put 'programa-talentos/:id' => 'programa_talentos#update'
      delete 'programa-talentos/:id' => 'programa_talentos#destroy'
      
      resources :vacantes

      get 'dotaciones-data', to: 'data#dotaciones', as: "dotaciones_data"
      # get 'altas-data' => 'data#altas'
      # get 'bajas-data' => 'data#bajas'
      get 'rotaciones-data', to: 'data#rotaciones', as: "rotaciones_data"
      get 'movimientos-data' => 'data#movimientos', as: "movimientos_data"
      get 'formaciones-data' => 'data#formaciones', as: "formaciones_data"
      get 'remuneraciones-data' => 'data#remuneraciones', as: "remuneraciones_data"
      get 'licencias-data' => 'data#licencias', as: "licencias_data"
      get 'vacaciones-data' => 'data#vacaciones', as: "vacaciones_data"
      get 'saldo-data' => 'data#saldo', as: "saldo_data"

      get 'estructura-data' => 'data#estructura', as: "estructura_data"
      get 'estructura_licencias' => 'data#estructura_licencias', as: "estructura_licencias"

      post 'user_logs', to: 'data#user_logs', as: 'user_logs'
      
    end
  end
end

app/models/licencia.rb
# == Schema Information
#
# Table name: licencias
#
#  id                  :integer          not null, primary key
#  fecha               :date
#  glosa_tipo_licencia :string
#  empleado_id         :integer
#  fecha_inicio        :date
#  fecha_termino       :date
#  dias_totales        :integer
#  dias_corridos       :integer
#  dias_habiles        :integer
#  periodo             :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  rut                 :string
#  periodo_anualizado  :string
#  tipo_licencia       :string
#



class Licencia < ActiveRecord::Base
  belongs_to :empleado

  scope :in_period, ->(period) { where('periodo = ?', period) unless period.blank?}

  PARAMETROS = [:dias_totales, :dias_corridos_periodo, :dias_habiles_periodo, :glosa_tipo_licencia, :rut, :periodo]

  scope :with_text, -> (text) {
    queries = PARAMETROS.map do |p|
      "#{p.to_s} ILIKE '%#{text}%'"
    end

    where(queries.join(" OR "))
  }

  def self.csv_import(data, periodo)
    row_index = 0
    ruts = []
    licencias = []
    begin
      CSV.foreach(data.tempfile, encoding: Encoding::UTF_8,headers: true, :col_sep => "\t") do |row, index|
        row_index = row_index+1
        empleado = Empleado.find_by_rut(row["rut"])
        if empleado
            licencia = empleado.licencias.new
            licencia.rut = row["rut"]
            licencia.dias_totales = row["dias_totales"]
            licencia.dias_corridos = row["dias_corridos_periodo"]
            licencia.dias_habiles = row["dias_habiles_periodo"]
            licencia.glosa_tipo_licencia = row["glosa_tipo_licencia"]
            # licencia.fecha_inicio = Date.strptime(row["fecha_inicio"], "%d/%m/%Y")
            # licencia.fecha_inicio = Date.strptime(row["fecha_termino"], "%d/%m/%Y")
            licencia.periodo = periodo
            licencia.periodo_anualizado = Date.strptime(row["periodo"], "%Y%m").strftime("%m-%Y")

            licencias << licencia
        else
          ruts << row["rut"].first(10)
        end
      end
      Licencia.import licencias
      return ruts
    rescue Exception => e
      puts e.message
      puts e.backtrace.inspect
      return row_index
    end
  end

end

app/controllers/admin/licencias_controller.rb
class Admin::LicenciasController < AdminController
  before_action -> { @sidebar_menu_item = :licencias }

  def index
    if params[:month].present? and params[:year].present?
      periodo = "#{params[:month]}-#{params[:year]}"
    else
      periodo = Date.today.strftime("%m-%Y")
    end

    @licencias = Licencia.in_period(periodo)

    if params[:query].present?
      @licencias = @licencias.with_text(params[:query])
    end

    @licencias = @licencias.paginate(page: params[:page]).order(fecha_inicio: :asc)
  end

  def show
    @licencia = Licencia.find(params[:id])
  end

  def new
    @empleado = Empleado.find_by!(rut: params[:rut])
    @licencia = @empleado.licencias.build
  end

  def create
    @empleado = Empleado.find_by!(rut: params[:licencia][:rut])
    @licencia = @empleado.licencias.build(licencia_params)

    if @licencia.save
      flash[:success] = "Entrada creada exitosamente."

      redirect_to admin_licencias_path
    else
      flash[:danger] = "Por favor corrija los errores indicados antes de continuar."

      render 'new'
    end
  end

  def edit
    @licencia = Licencia.find(params[:id])
  end

  def update
    @licencia = Licencia.find(params[:id])

    if @licencia.update_attributes(licencia_params)
      flash[:success] = "Entrada actualizada exitosamente."
    else
      flash[:danger] = "Por favor corrija los errores indicados antes de continuar."
    end

    render 'edit'
  end

  def destroy
    Licencia.find(params[:id]).destroy

    flash[:success] = "Entrada eliminada exitosamente."

    redirect_to admin_licencias_path
  end

  private

  def licencia_params
    params.require(:licencia).permit(:glosa_tipo_licencia, :dias_totales, :dias_corridos, :dias_habiles, :rut, :periodo_anualizado,:periodo)
  end
end

app/controllers/api/v1/old/licencias_controller.rb
class Api::V1::LicenciasController < Api::V1::BaseController
        respond_to :json


  def index
    if ( params[:month] and !(params[:month]).empty? and params[:year] and !(params[:year]).empty? )
      period = params[:month]+"-"+params[:year]
      @licencias = Licencia.in_period(period)
    else
      period = Date.today.strftime("%m-%Y")
      @licencias = Licencia.in_period(period)
    end
    render json: serialize_models(@licencias)
  end

  def show
    @licencia = Licencia.find(params[:id])
    render json: serialize_model(@licencia)
  end


  def create
    empleado = Empleado.find_by_rut(params[:data][:attributes][:rut])
    licencia = empleado.licencias.new(licencia_params)
    if licencia.save
      render json: serialize_model(licencia), status: 201
    else
      render json: serialized_errors(licencia), status: 422
    end
  end

  def update
    licencia = Licencia.find(params[:id])
    attrs = params[:data][:attributes]
    if licencia.update_attributes(licencia_params)
      render json: serialize_model(licencia), status: 201
    else
      render json: serialized_errors(licencia), status: 422
    end
  end

  def destroy
    licencia = Licencia.find(params[:id])
    licencia.destroy!
    render json: "", status: 204

  end

  private


    def licencia_params
      params.require(:data).require(:attributes).permit(:fecha, :rut, :glosa_tipo_licencia, :fecha_inicio, :fecha_termino, :dias_totales, :dias_corridos, :dias_habiles, :periodo, :empleado_id, :periodo_anualizado)
    end


#  fecha               :date
#  glosa_tipo_licencia :string
#  empleado_id         :integer
#  fecha_inicio        :date
#  fecha_termino       :date
#  dias_totales        :integer
#  dias_corridos       :integer
#  dias_habiles        :integer
#  periodo             :string

end

app/views/admin/licencias/_form.html.erb
<div class="form-group">
  <label for="empleado">Empleado</label>
  <input name="empleado" type="text" value="<%= @licencia.empleado.nombre.split(" ").first.capitalize %> <%= @licencia.empleado.apellidos.split(" ").first.capitalize %> (RUT: <%= @licencia.empleado.rut_beautified %>)" class="form-control" readonly>
</div>
<%= f.hidden_field :rut, value:  @licencia.empleado.rut%>

<%= f.input :glosa_tipo_licencia %>

<%= f.input :dias_totales %>

<%= f.input :dias_corridos %>

<%= f.input :dias_habiles %>

<%= f.input :periodo_anualizado %>

<%= f.input :periodo %>

<hr/>

<div class="text-center">
  <%= f.button :submit, "Enviar", class: "btn btn-primary" %>
</div>

app/views/admin/licencias/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Editar licencia: <%= @licencia.id %></h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for @licencia, url: admin_licencia_path(@licencia), method: :put do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/admin/licencias/index.html.erb
<% provide(:upload_modal_type, "licencias") %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Gestión de licencias</h4>
  </div>
  <div class="panel-body">
    <%= render "shared/backend/controls" %>

    <div class="well">
      <div class="row">
        <div class="col-md-6">
          <%= render "shared/backend/date_selector", resource: "licencias" %>
        </div>
      </div>
    </div>

    <div class="text-center">
      <%= will_paginate @empleados, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-bordered table-hover table-striped">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">Empleado</th>
          <th>Información</th>
          <th class="text-center">Tipo</th>
          <th class="text-center">Duracion</th>
          <th class="text-center"><%= fa_icon("cogs") %></th>
        </tr>
      </thead>
      <tbody>
        <% @licencias.each do |licencia| %>
          <tr>
            <td class="text-center"><%= licencia.id %></td>
            <td class="text-center">
              <%= link_to admin_empleado_path licencia.empleado do %>
                <%= licencia.empleado.nombre.split(" ").first.capitalize %> <%= licencia.empleado.apellidos.split(" ").first.capitalize %>
              <% end %>
            </td>
            <td class="small">
              <strong>Días Hábiles:</strong> <%= licencia.dias_habiles %><br/>
              <strong>Dias Corridos:</strong> <%= licencia.dias_corridos %><br/>
            </td>
            <td class="text-center"><%= licencia.glosa_tipo_licencia %></td>
            <td class="text-center"><%= licencia.dias_totales %></td>
            <td class="text-center">
              <div class="dropdown">
                <button class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown"><%= fa_icon("caret-down") %></button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="<%= edit_admin_licencia_path licencia %>">Editar</a></li>
                    <li><%= link_to "Eliminar", admin_licencia_path(licencia), method: :delete, data: {confirm: "Esta acción es irreversible. ¿Está seguro que desea continuar?"} %></li>
                  </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pull-right"> TOTAL: <%=  number_with_delimiter @licencias.count.to_s%></div>

    <div class="text-center">
      <%= will_paginate @empleados, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/admin/licencias/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Gestión de licencias</h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for @licencia, url: admin_licencias_path, method: :post do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>