config/routes.rb
Rails.application.routes.draw do

  # Vistas para el divisional

  # get '/altas', to: 'managers#altas', as: 'altas'
  # get '/bajas', to: 'managers#bajas', as: 'bajas'
  get '/dotaciones', to: 'managers#dotaciones', as: 'dotaciones'
  get '/manager', to: 'managers#dotaciones', as: 'manager'
  get '/movimientos', to: 'managers#movimientos', as: 'movimientos'
  get '/formaciones', to: 'managers#formaciones', as: 'formaciones'
  get '/rotaciones', to: 'managers#rotaciones', as: 'rotaciones'
  get '/remuneraciones', to: 'managers#remuneraciones', as: 'remuneraciones'
  get '/vacaciones', to: 'managers#vacaciones', as: 'vacaciones'
  get '/saldo-vacaciones', to: 'managers#saldo', as: 'saldo'
  # get '/personas', to: 'managers#personas', as: 'personas'
  get '/licencias', to: 'managers#licencias', as: 'licencias'
  #post '/entrada', to: 'managers#entrada', as: 'entrada'
  
  devise_scope :user do
    get 'login', to: 'users/sessions#create'
  end
  get '/users/entrada', to: 'managers#entrada', as: 'user_with_params'
  # post '/users/entrada', to: 'managers#entrada', as: 'user_with_params'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'managers#index'

  namespace :admin do
    post ':model_type/upload', to: 'upload#create', as: :upload
    post ':model_type/remove', to: 'upload#remove', as: :remove
    post '/generate', to: 'upload#generate', as: :generate
    get '/ordenar_gerencias', to: 'vacantes#ordenar_gerencias', as: :ordenar_gerencias
    get '/ordenar_divisiones', to: 'vacantes#ordenar_divisiones', as: :ordenar_divisiones
    post '/crear_orden_gerencias', to: 'vacantes#crear_orden_gerencias', as: :crear_orden_gerencias
    post '/crear_orden_divisiones', to: 'vacantes#crear_orden_divisiones', as: :crear_orden_divisiones
    get '/user/:id/log', to: 'users#log', as: :log_user
    resources :formaciones
    resources :licencias
    resources :empleados
    resources :users
    resources :movimientos
    resources :egresos
    resources :posiciones
    resources :retribuciones
    resources :vacaciones
    resources :vacantes
    resources :user_logs

    root "empleados#index", as: :home
  end

  post "update_role" => "roles#update", as: "update_role"
  resources :users do
    get 'resend_invite', to: "users#resend_invite", as: "resend_invite"
  end

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post 'upload' => 'upload#create'
      get 'remove' => 'upload#remove'
      get 'generate' => 'upload#generate'
      get 'programa-talentos' => 'programa_talentos#index'
      get 'programa-talentos/:id' => 'programa_talentos#show'
      post 'programa-talentos' => 'programa_talentos#create'
      put 'programa-talentos/:id' => 'programa_talentos#update'
      delete 'programa-talentos/:id' => 'programa_talentos#destroy'
      
      resources :vacantes

      get 'dotaciones-data', to: 'data#dotaciones', as: "dotaciones_data"
      # get 'altas-data' => 'data#altas'
      # get 'bajas-data' => 'data#bajas'
      get 'rotaciones-data', to: 'data#rotaciones', as: "rotaciones_data"
      get 'movimientos-data' => 'data#movimientos', as: "movimientos_data"
      get 'formaciones-data' => 'data#formaciones', as: "formaciones_data"
      get 'remuneraciones-data' => 'data#remuneraciones', as: "remuneraciones_data"
      get 'licencias-data' => 'data#licencias', as: "licencias_data"
      get 'vacaciones-data' => 'data#vacaciones', as: "vacaciones_data"
      get 'saldo-data' => 'data#saldo', as: "saldo_data"

      get 'estructura-data' => 'data#estructura', as: "estructura_data"
      get 'estructura_licencias' => 'data#estructura_licencias', as: "estructura_licencias"

      post 'user_logs', to: 'data#user_logs', as: 'user_logs'
      
    end
  end
end

app/views/shared/backend/_controls.html.erb
<div class="row controls">
  <div class="col-xs-9">
    <%if controller.controller_name.classify != "Vacante"%>
      <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#upload-modal">
        <%= fa_icon("upload") %> Cargar información
      </button>
    <%else%>
      <%= link_to admin_generate_path(periodo: "#{params[:month]||Date.today.month}-#{params[:year]||Date.today.year}"), class: "btn btn-sm btn-info",method: :post do%>
            <%= fa_icon("upload") %> Generar Estructura
      <%end%>
    <%end%>
    <%= link_to admin_remove_path(controller.controller_name.classify, periodo: "#{params[:month]||Date.today.month}-#{params[:year]||Date.today.year}"), class: "btn btn-sm btn-danger",method: :post do%>
          <%= fa_icon("trash-o") %> Eliminar información
    <%end%>

  </div>
  <div class="col-xs-3 text-right">
    <%= render "shared/backend/search" %>
  </div>
</div>

app/views/shared/backend/_date_selector.html.erb
<div>
  <strong>Filtrar por período:</strong>&nbsp;&nbsp; <%= date_select(:periodo, :fecha, {discard_day: true, order: [:month, :year], default: Date.parse("#{params[:year]||Date.today.year}-#{params[:month]||Date.today.month}-01")}, {data: {resource: resource}}) %>
</div>

app/views/shared/backend/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= flash_demux(k) %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

    <%= v.html_safe %>
  </div>
<% end %>

app/views/shared/backend/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%= image_tag "logo-small.png" %>
      </a>
    </div>

    <p class="navbar-text">
      <strong>Apps Personas</strong>
    </p>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><%= current_user.nombre_completo %> <%= image_tag "anon.jpg", height: "20", class: "img-circle", id: "profile-img" %></a></li>
    </ul>
  </div>
</nav>

app/views/shared/backend/_log_table.html.erb
<div class="panel-body">

    <div class="text-center">
        <%= will_paginate @user_logs, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-bordered table-hover table-striped">
        <thead>
            <colgroup>
                <col>
                <col>
                <col>
                <col>
                <col>
                <col>
                <col>
                <col>
            </colgroup>
            <tr>
                <th>Apellidos</th>
                <th>Nombres</th>
                <th class="text-center">RUT</th>
                <th class="text-center">Gerencia</th>
                <th class="text-center">División</th>
                <th class="text-center">Período</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Fuente</th>
            </tr>
        </thead>
        <tbody>
            <% @user_logs.each do |log| %>
                <tr>
                    <td>
                        <%= log.user.metadata['apellidos'] %>
                    </td>
                    <td>
                        <%= log.user.metadata['nombres'] %>
                    </td>
                    <td class="text-center">
                        <%= log.user.rut %>
                    </td>
                    <td class="text-center">
                        <%= log.gerencia %>
                    </td>
                    <td class="text-center">
                        <%= log.division %>
                    </td>
                    <td class="text-center">
                        <%= log.period %>
                    </td>
                    <td class="text-center">
                        <%= log.created_at.strftime('%d-%m-%y') %>
                    </td>
                    <td class="text-center">
                        <%= log.source %>
                    </td>
                </tr>
                <% end %>
        </tbody>
    </table>

    <div class="text-center">
        <%= will_paginate @user_logs, renderer: BootstrapPagination::Rails %>
    </div>
</div>

app/views/shared/backend/_search.html.erb
<%= simple_form_for "search", method: :get, url: request.original_url, html: {id: "search_form"} do |f| %>
  <% if params[:month].present? %>
    <%= f.input "month", as: :hidden, input_html: {name: "month", value: params[:month]} %>
  <% end %>
  <% if params[:year].present? %>
    <%= f.input "year", as: :hidden, input_html: {name: "year", value: params[:year]} %>
  <% end %>
  <div class="input-group">
    <%= f.input "query", label: false, wrapper: false, required: false, input_html: {name: "query", class: "input-sm", placeholder: "Buscar...", value: params[:query]} %>
    <span class="input-group-btn">
      <button class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="bottom" data-title="Vaciar consulta" type="button" id="clear_search">
        <%= fa_icon("times") %>
      </button>
      <button class="btn btn-sm btn-default" type="submit">
        <%= fa_icon("search") %>
      </button>
    </span>
  </div><!-- /input-group -->
<% end %>

app/views/shared/backend/_sidebar.html.erb
<div class="sidebar-top-wrapper">
  <div class="sidebar-top">
    <%= render "shared/backend/sidebar_user" %>

    <div class="banner-image"></div>
  </div>
</div>

<div class="sidebar">
  <%= render "shared/backend/sidebar_menu" %>
</div>

app/views/shared/backend/_sidebar_menu.html.erb
<ul class="sidebar-menu">
  <%= content_tag :li, class: @sidebar_menu_item == :empleados ? "active" : nil do %>
    <%= link_to admin_empleados_path do %>
      <%= fa_icon("user-circle-o") %>
      Empleados
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :posiciones ? "active" : nil do %>
    <%= link_to admin_posiciones_path do %>
      <%= fa_icon("sitemap") %>
      Posiciones
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :egresos ? "active" : nil do %>
    <%= link_to admin_egresos_path do %>
      <%= fa_icon("chevron-right") %>
      Egresos
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :formaciones ? "active" : nil do %>
    <%= link_to admin_formaciones_path do %>
      <%= fa_icon("mortar-board") %>
      Formación
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :movimientos ? "active" : nil do %>
    <%= link_to admin_movimientos_path do %>
      <%= fa_icon("repeat") %>
      Movimientos
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :retribuciones ? "active" : nil do %>
    <%= link_to admin_retribuciones_path do %>
      <%= fa_icon("money") %>
      Ajustes de renta
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :licencias ? "active" : nil do %>
    <%= link_to admin_licencias_path do %>
      <%= fa_icon("heart-o") %>
      Licencias
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :vacaciones ? "active" : nil do %>
    <%= link_to admin_vacaciones_path do %>
      <%= fa_icon("plane") %>
      Vacaciones
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :vacantes ? "active" : nil do %>
    <%= link_to admin_vacantes_path do %>
      <%= fa_icon("building") %>
      Estructura
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :usuarios ? "active" : nil do %>
    <%= link_to admin_users_path do %>
      <%= fa_icon("users") %>
      Usuarios
    <% end %>
  <% end %>
  <%= content_tag :li, class: @sidebar_menu_item == :user_logs ? "active" : nil do %>
    <%= link_to admin_user_logs_path do %>
      <%= fa_icon("book") %>
      Log de Usuarios
    <% end %>
  <% end %>
  <%= content_tag :li do %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <%= fa_icon("sign-out") %>
      Cerrar sesión
    <% end %>
  <% end %>
</ul>

app/views/shared/backend/_sidebar_user.html.erb
<div class="sidebar-user">
  <%= image_tag "anon.jpg", width: "100", class: "img-circle" %>
  <h4><%= current_user.nombre_completo %></h4>
  <span class="sidebar-role">Administrador</span>

  <%= link_to root_path, class: "btn btn-danger btn-sm" do %>
    <%= fa_icon("bar-chart") %> Ir al Dashboard
  <% end %>
</div>

app/views/shared/backend/_upload_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="upload-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cargar archivo</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-7">
                        <h4>Ayuda sobre el formato del fichero de subida</h4>
                        <div class="alert alert-info">Siga las siguientes instrucciones para cargar el archivo correctamente.</div>
                        <h5>Paso 1: guarde el archivo</h5>
                        <ul>
                            <li>En Excel, guarde el archivo desde el menú: <code>Archivo -> Guardar como -> Texto delimitado por tabulaciones (.txt).</code></li>
                        </ul>

                        <h5>Paso 2: conviértalo a una codificación válida</h5>
                        <ul>
                            <li>En sistemas <strong>OS X o Linux</strong>, convierta el archivo usando el terminal y el comando:
                                <p>
                                    <kbd>iconv -f iso-8859-1 -t utf-8 archivo-original.csv > archivo-utf8.csv</kbd>
                                </p>
                            </li>
                            <li>En <strong>Windows</strong> utilice un programa <code>Notepad++</code> o similar. Abra el fichero con este programa y utilizar la opción de menú <code>Codificación -> Convertir a UTF-8</code>. Una vez hecho, guarde el fichero.</li>
                        </ul>

                        <h5>Paso 3: verifique las columnas</h5>
                        <ul>
                            <% if (model_type == "egresos")%>
                                <li>
                                    Comprueba que el archivo TSV tiene las siguientes columnas: <code>Rut</code>, <code>Tipo</code>, <code>periodo</code>, <code>Piramide</code>, <code>Contrato</code>, <code>División_UR</code>, <code>Gerencia_UR</code>,<code> Empresa</code>,
                                    <code>considero España(rellenado a "n" o en blanco)</code>, <code>Tipo Renta</code>, <code>Cargo</code>, <code>Num Hijos</code>, <code>Estado Civil</code>.<br>
                                    <strong>Debe coincidir exactamente</strong>, o en caso contrario la importación puede arrojar errores.
                                </li>
                                <% elsif (model_type == "empleados")%>
                                    <li>
                                        Comprueba que el archivo TSV tiene las siguientes columnas: <code>rut</code>, <code>Sexo</code>, <code>Nacimiento (con el formato 31/12/99)</code>, <code>Inicio (con el formato 31/12/99)</code>, <code>Termino (con el formato 31/12/99)</code>,
                                        <code>Nombres</code>, <code>Apellidos</code>.<br>
                                        <strong>Debe coincidir exactamente</strong>
                                    </li>
                                    <% elsif (model_type == "formaciones")%>
                                        <li>Compruebe que el archivo TSV tiene las siguientes columnas: <code>rut_fncro</code>, <code>materia</code>, <code>nom_curso</code>, <code>Modalidad</code>, <code>periodo(Formato 201506)</code>, <code>HORAS</code>,<code>asistencia(sólo se contarán aquellos con valor "Presente")</code>.
                                            <strong>Debe coincidir exactamente</strong>, o en caso contrario la importación puede arrojar errores.</li>
                                        <% elsif (model_type == "movimientos")%>
                                            <li>
                                                Comprueba que el archivo TSV tiene las siguientes columnas: <code>pos_rut</code>, <code>tipo_cambio_posicion</code>, <code>pos_periodo(Formato 201506)</code>.<br>
                                                <strong>Debe coincidir exactamente</strong>
                                            </li>

                                            <% elsif (model_type == "posiciones")%>
                                                <li>
                                                    Comprueba que el archivo TSV tiene las siguientes columnas: <code>rut</code>, <code>Piramide</code>, <code>Contrato</code>, <code>División_UR</code>, <code>Gerencia_UR</code>, <code>Empresa</code>, <code>considero España(rellenado a "n" o en blanco)</code>,
                                                    <code>Tipo Renta</code>, <code>Cargo</code>, <code>Num Hijos</code>, <code>Estado Civil</code>, <code>saldo vacaciones </code>, <code>periodos pendientes vacaciones</code>.<br>
                                                    <strong>Debe coincidir exactamente</strong>
                                                </li>
                                                <% elsif (model_type == "retribuciones")%>
                                                    <li>
                                                        Comprueba que el archivo TSV tiene las siguientes columnas: <code>Sim Rutfun</code>, <code>Tipo Mov</code>, <code>Resto Año (valor sin comas ni puntos)</code>,<code>porcentaje (valor como 0.25)</code>,
                                                        <code>12 Meses(valor sin comas ni puntos)</code>, <code>período (formato 201512)</code>.<br>
                                                        <strong>Debe coincidir exactamente</strong>
                                                    </li>
                                                    <% elsif (model_type == "licencias")%>
                                                        <li>
                                                            Comprueba que el archivo TSV tiene las siguientes columnas: <code>rut</code>, <code>dias_totales</code>, <code>dias_corridos_periodo</code>, <code>dias_habiles_periodo</code>, <code>glosa_tipo_licencia</code>,
                                                            <code>periodo (formato 201512)</code>.<br>
                                                            <strong>Debe coincidir exactamente</strong>
                                                        </li>
                                                        <% elsif (model_type == "vacaciones")%>
                                                            <li>
                                                                Comprueba que el archivo TSV tiene las siguientes columnas: <code>rut</code>, <code>consumo</code>, <code>10_dias (SI o NO)</code>.<br>
                                                                <strong>Debe coincidir exactamente</strong>
                                                            </li>
                                                            <%end%>
                        </ul>
                    </div>
                    <div class="col-md-5">
                        <h4>Cargar archivo</h4>

                        <div class="alert alert-danger" id="upload_file_invalid" style="display: none;">El archivo cargado no es válido. Recuerde que este debe ser un archivo CSV.</div>

                        <%= simple_form_for "upload", method: :post, url: admin_upload_path(model_type) do |f| %>
                            <%= f.input :file, as: :file, label: "Click aquí para seleccionar un archivo", input_html: {style: "display: none;"}, required: false %>
                                <% if (model_type == "empleados")%>
                                    <style>
                                        .upload_periodo {
                                            display: none;
                                        }
                                    </style>
                                    <%end%>
                                        <%= f.input :periodo, as: :date, required: false, order: [:month, :year], start_year: 2015 %>

                                            <%= f.button :submit, "Cargar archivo", class: "btn btn-lg btn-block btn-success", disabled: true, id: "upload_submit" %>
                                                <% end %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>