config/routes.rb
Rails.application.routes.draw do

  # Vistas para el divisional

  # get '/altas', to: 'managers#altas', as: 'altas'
  # get '/bajas', to: 'managers#bajas', as: 'bajas'
  get '/dotaciones', to: 'managers#dotaciones', as: 'dotaciones'
  get '/manager', to: 'managers#dotaciones', as: 'manager'
  get '/movimientos', to: 'managers#movimientos', as: 'movimientos'
  get '/formaciones', to: 'managers#formaciones', as: 'formaciones'
  get '/rotaciones', to: 'managers#rotaciones', as: 'rotaciones'
  get '/remuneraciones', to: 'managers#remuneraciones', as: 'remuneraciones'
  get '/vacaciones', to: 'managers#vacaciones', as: 'vacaciones'
  get '/saldo-vacaciones', to: 'managers#saldo', as: 'saldo'
  # get '/personas', to: 'managers#personas', as: 'personas'
  get '/licencias', to: 'managers#licencias', as: 'licencias'
  #post '/entrada', to: 'managers#entrada', as: 'entrada'
  
  devise_scope :user do
    get 'login', to: 'users/sessions#create'
  end
  get '/users/entrada', to: 'managers#entrada', as: 'user_with_params'
  # post '/users/entrada', to: 'managers#entrada', as: 'user_with_params'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'managers#index'

  namespace :admin do
    post ':model_type/upload', to: 'upload#create', as: :upload
    post ':model_type/remove', to: 'upload#remove', as: :remove
    post '/generate', to: 'upload#generate', as: :generate
    get '/ordenar_gerencias', to: 'vacantes#ordenar_gerencias', as: :ordenar_gerencias
    get '/ordenar_divisiones', to: 'vacantes#ordenar_divisiones', as: :ordenar_divisiones
    post '/crear_orden_gerencias', to: 'vacantes#crear_orden_gerencias', as: :crear_orden_gerencias
    post '/crear_orden_divisiones', to: 'vacantes#crear_orden_divisiones', as: :crear_orden_divisiones
    get '/user/:id/log', to: 'users#log', as: :log_user
    resources :formaciones
    resources :licencias
    resources :empleados
    resources :users
    resources :movimientos
    resources :egresos
    resources :posiciones
    resources :retribuciones
    resources :vacaciones
    resources :vacantes
    resources :user_logs

    root "empleados#index", as: :home
  end

  post "update_role" => "roles#update", as: "update_role"
  resources :users do
    get 'resend_invite', to: "users#resend_invite", as: "resend_invite"
  end

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post 'upload' => 'upload#create'
      get 'remove' => 'upload#remove'
      get 'generate' => 'upload#generate'
      get 'programa-talentos' => 'programa_talentos#index'
      get 'programa-talentos/:id' => 'programa_talentos#show'
      post 'programa-talentos' => 'programa_talentos#create'
      put 'programa-talentos/:id' => 'programa_talentos#update'
      delete 'programa-talentos/:id' => 'programa_talentos#destroy'
      
      resources :vacantes

      get 'dotaciones-data', to: 'data#dotaciones', as: "dotaciones_data"
      # get 'altas-data' => 'data#altas'
      # get 'bajas-data' => 'data#bajas'
      get 'rotaciones-data', to: 'data#rotaciones', as: "rotaciones_data"
      get 'movimientos-data' => 'data#movimientos', as: "movimientos_data"
      get 'formaciones-data' => 'data#formaciones', as: "formaciones_data"
      get 'remuneraciones-data' => 'data#remuneraciones', as: "remuneraciones_data"
      get 'licencias-data' => 'data#licencias', as: "licencias_data"
      get 'vacaciones-data' => 'data#vacaciones', as: "vacaciones_data"
      get 'saldo-data' => 'data#saldo', as: "saldo_data"

      get 'estructura-data' => 'data#estructura', as: "estructura_data"
      get 'estructura_licencias' => 'data#estructura_licencias', as: "estructura_licencias"

      post 'user_logs', to: 'data#user_logs', as: 'user_logs'
      
    end
  end
end

app/views/shared/_alert.html.erb
<script>
var opts = {
	"closeButton": true,
	"debug": false,
	"positionClass": "toast-top-full-width",
	"onclick": null,
	"showDuration": "300",
	"hideDuration": "1000",
	"timeOut": "5000",
	"extendedTimeOut": "1000",
	"showEasing": "swing",
	"hideEasing": "linear",
	"showMethod": "fadeIn",
	"hideMethod": "fadeOut"
};

toastr.error("", "<%= alert%>", opts);
</script>

app/views/shared/_form_error.html.erb
<script>
var opts = {
  "closeButton": true,
  "debug": false,
  "positionClass": "toast-top-full-width",
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
};

toastr.error("", "Error en el formulario", opts);
</script>

app/views/shared/_manager_footer.html.erb
<!-- Footer -->
<footer class="main">


  &copy; 2016 <strong>Banco Santander</strong>

</footer>

app/views/shared/_manager_links.html.erb
            <ul class="list-inline quick-links" style="line-height: 26px;">
              <li><a onclick="clickManagerLink('Dotaciones','<%= dotaciones_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Dotaciones</a>
              </li>
              <li><a onclick="clickManagerLink('Rotaciones','<%= rotaciones_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Egresos</a>
              </li>
              <li><a onclick="clickManagerLink('Movimientos','<%= movimientos_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Promociones</a>
              </li>
              <li><a onclick="clickManagerLink('Remuneraciones','<%= remuneraciones_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Compensaciones</a>
              </li>
              <li><a onclick="clickManagerLink('Formaciones','<%= formaciones_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Formaciones</a>
              </li>
              <li><a onclick="clickManagerLink('Licencias','<%= licencias_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Licencias</a>
              </li>
              <li><a onclick="clickManagerLink('Vacaciones','<%= vacaciones_path+"?division="+url_encode(@current_division)+"&periodo="+@periodo %>')">Vacaciones</a>
              </li>
            </ul>

<script>

const clickManagerLink = function(gerencia, url){
    var user_logs_params = {};
    Object.assign(user_logs_params, {period: '<%= @periodo %>', gerencia: gerencia, division: '<%= @current_division%>' , source: 'Manager Link' });
    saveUserLog(user_logs_params);
    goToUrl(url);
}

</script>

app/views/shared/_manager_modal.html.erb
<!-- Sample Modal (Default skin) -->
<div class="modal fade" id="sample-modal-dialog-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Widget Options - Default Modal</h4>
      </div>
      
      <div class="modal-body">
        <p>Now residence dashwoods she excellent you. Shade being under his bed her. Much read on as draw. Blessing for ignorant exercise any yourself unpacked. Pleasant horrible but confined day end marriage. Eagerness furniture set preserved far recommend. Did even but nor are most gave hope. Secure active living depend son repair day ladies now.</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- Sample Modal (Skin inverted) -->
<div class="modal invert fade" id="sample-modal-dialog-2">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Widget Options - Inverted Skin Modal</h4>
      </div>
      
      <div class="modal-body">
        <p>Now residence dashwoods she excellent you. Shade being under his bed her. Much read on as draw. Blessing for ignorant exercise any yourself unpacked. Pleasant horrible but confined day end marriage. Eagerness furniture set preserved far recommend. Did even but nor are most gave hope. Secure active living depend son repair day ladies now.</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- Sample Modal (Skin gray) -->
<div class="modal gray fade" id="sample-modal-dialog-3">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Widget Options - Gray Skin Modal</h4>
      </div>
      
      <div class="modal-body">
        <p>Now residence dashwoods she excellent you. Shade being under his bed her. Much read on as draw. Blessing for ignorant exercise any yourself unpacked. Pleasant horrible but confined day end marriage. Eagerness furniture set preserved far recommend. Did even but nor are most gave hope. Secure active living depend son repair day ladies now.</p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_manager_sidebar.html.erb
<div class="sidebar-menu">

  <div class="bottom-sidebar">
    <div class="sidebar-collapse">
      <a href="#" class="sidebar-collapse-icon with-animation">
        <!-- <i class="entypo-menu size-icon"></i> -->
      <!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
        <i class="entypo-menu"></i>
      </a>
    </div>



    <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
    <div class="sidebar-mobile-menu visible-xs">
      <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
        <i class="entypo-menu"></i>

      </a>
    </div>
  </div>


  <div class="photo-profile">
    <!-- <div id="circle">
      <%= image_tag("bow.jpg", alt: "Logo")%>
    </div> -->

    <h3><%= current_user.nombre_completo %></h3>
    <h4>
      <%if current_user.rol != 2%>
       <%= current_user.role %></h4>
       <%else%>
       <%= link_to current_user.role,admin_home_path %></h4>

       <%end%>
    <p>
    <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "¿Seguro que desea salir?"} do%>
      Salir <i class="fa fa-sign-out right"></i>
    <% end %>
    </p>
  </div>

  <%if (current_user.rol == 1 or  current_user.rol == 2)%>
    <ul id="main-menu" class="">
      <li class="dota has-sub">
        <a>
          <%=image_tag "icono_dota.png"%>
          <span>Dotaciones</span>
        </a>
        <ul>
          <li class="global">
            <a onclick="clickSideBarLink('Dotaciones', 'Global', '<%= dotaciones_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each_with_index do |division, index|%>
            <li class="<%=index %>">
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= dotaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="rota">
        <a>
          <%=image_tag "icono_rotacion.png"%>
          <span>Egresos</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Rotaciones', 'Global', '<%= rotaciones_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= rotaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
        </a>
      </li>
      <li class="movimientos">
        <a>
          <%=image_tag "icono_gest.png"%>
          <span>Promociones</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Movimientos', 'Global', '<%= movimientos_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= movimientos_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="remuneraciones">
        <a>
          <%=image_tag "icono_rem.png"%>
          <span>Compensaciones</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Remuneraciones', 'Global', '<%= remuneraciones_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= remuneraciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="forma">
        <a>
          <%=image_tag "icono_formacion.png"%>
          <span>Formaciones</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Formaciones', 'Global', '<%= formaciones_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= formaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="licencias">
        <a>
          <%=image_tag "ico_licencias.png", width: "10px"%>
          <span>Licencias</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Licencias', 'Global', '<%= licencias_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>

            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= licencias_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="vacaciones">
        <a>
          <%=image_tag "icono_vacacion.png"%>
          <span>Vacaciones</span>
        </a>
        <ul>
          <li>
            <a onclick="clickSideBarLink('Vacaciones', 'Global', '<%= vacaciones_path+"?periodo="+@periodo %>')"> Global </a>
          </li>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= vacaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>


  </ul>
  <%else%>
  <ul id="main-menu" class="">
      <li class="dota has-sub">
        <a onclick="clickSideBarLink('Dotaciones', 'Global', '<%= dotaciones_path+"?periodo="+@periodo %>')" >
          <%=image_tag "icono_dota.png"%>
          <span>Dotaciones</span>
        </a>
        <ul>
          <% @divisiones.each_with_index do |division, index|%>
            <li class="<%=index %>">
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= dotaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="rota">
        <a onclick="clickSideBarLink('Rotaciones', 'Global', '<%= rotaciones_path+"?periodo="+@periodo %>')" >
          <%=image_tag "icono_rotacion.png"%>
          <span>Egresos</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= rotaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
        </a>
      </li>
      <li class="movimientos">
        <a onclick="clickSideBarLink('Movimientos', 'Global', '<%= movimientos_path+"?periodo="+@periodo %>')" >
          <%=image_tag "icono_gest.png"%>
          <span>Promociones</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= movimientos_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="remuneraciones">
        <a onclick="clickSideBarLink('Remuneraciones', 'Global', '<%= remuneraciones_path+"?periodo="+@periodo %>')"  >
          <%=image_tag "icono_rem.png"%>
          <span>Compensaciones</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= remuneraciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="forma">
        <a onclick="clickSideBarLink('Formaciones', 'Global', '<%= formaciones_path+"?periodo="+@periodo %>')" >
          <%=image_tag "icono_formacion.png"%>
          <span>Formaciones</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= formaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="licencias">
        <a onclick="clickSideBarLink('Licencias', 'Global', '<%= licencias_path+"?periodo="+@periodo %>')">
          <%=image_tag "ico_licencias.png"%>
          <span>Licencias</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= licencias_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="vacaciones">
        <a onclick="clickSideBarLink('Vacaciones', 'Global', '<%= vacaciones_path+"?periodo="+@periodo %>')" >
          <%=image_tag "icono_vacacion.png"%>
          <span>Vacaciones</span>
        </a>
        <ul>
          <% @divisiones.each do |division|%>
            <li>
              <a 
              onclick="clickSideBarLink('Dotaciones', '<%= division %>', '<%= vacaciones_path+"?division="+url_encode(division)+"&periodo="+@periodo %>')">
               <%= division %> </a>
            </li>
          <% end %>
        </ul>
      </li>


  </ul>


  <%end%>

</div>

<script>
    
  const clickSideBarLink = function(gerencia ,division ,url){
    var user_logs_params = {};
    Object.assign(user_logs_params, {period: '<%= @periodo %>', gerencia: gerencia, division: division, source: 'Barra Lateral' });
    saveUserLog(user_logs_params);
    goToUrl(url);
  }

</script>

app/views/shared/_manager_topbar.html.erb
    <div class="row row-header">
      <div class="img-header">
<!--         <img src="assets/economia.jpg" alt="">
 -->      </div>
    </div>

app/views/shared/_notice.html.erb
<script>
var opts = {
	"closeButton": true,
	"debug": false,
	"positionClass": "toast-top-full-width",
	"onclick": null,
	"showDuration": "300",
	"hideDuration": "1000",
	"timeOut": "5000",
	"extendedTimeOut": "1000",
	"showEasing": "swing",
	"hideEasing": "linear",
	"showMethod": "fadeIn",
	"hideMethod": "fadeOut"
};

toastr.success("<%= notice %>", opts);
</script>

app/views/shared/_public_footer.html.erb
  <!-- Footer Widgets -->
<section class="footer-widgets">

  <div class="container">

    <div class="row">

      <div class="col-sm-6">

        <a href="#">
          <img src="assets/images/logo@2x.png" width="100" />
        </a>

        <p>
          Vivamus imperdiet felis consectetur onec eget orci adipiscing nunc. <br />
          Pellentesque fermentum, ante ac interdum ullamcorper.
        </p>

      </div>

      <div class="col-sm-3">

        <h5>Dirección</h5>

        <p>
          Loop, Inc. <br />
          795 Park Ave, Suite 120 <br />
          San Francisco, CA 94107
        </p>

      </div>

      <div class="col-sm-3">

        <h5>Contact</h5>

        <p>
          Phone: +1 (52) 2215-251 <br />
          Fax: +1 (22) 5138-219 <br />
        </p>

      </div>

    </div>

  </div>

</section>



<!-- Site Footer -->
<footer class="site-footer">

  <div class="container">

    <div class="row">

      <div class="col-sm-6">
        Copyright &copy; Neon - All Rights Reserved.
      </div>

      <div class="col-sm-6">

        <ul class="social-networks text-right">
          <li>
            <a href="#">
              <i class="entypo-instagram"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="entypo-twitter"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="entypo-facebook"></i>
            </a>
          </li>
        </ul>

      </div>

    </div>

  </div>

</footer>

app/views/shared/_public_header.html.erb
  <div class="site-header-container container">

  <div class="row">

    <div class="col-md-12">

      <header class="site-header">

        <section class="site-logo">

          <a href="<%= root_path %>">
            <%= image_tag "logo-light.png", width: 120 %>
<!--             <img src="assets/images/logo@2x.png" width="120" />
 -->       </a>

        </section>

        <nav class="site-nav">

          <ul class="main-menu hidden-xs" id="main-menu">
            <% if user_signed_in?%>
              <li>
                <a href="<%= manager_path %>">
                  <div class="label label-secondary">Dashboard</div>
                </a>
              </li>
              <li>
              <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "Are you sure you want to exit?"} do%>
                Sign Out <i class="fa fa-sign-out right"></i>
              <% end %>
              </li>
            <%else%>
              <li>
                <a href="<%= new_user_registration_path %>">
                  <div class="label label-secondary">Sign Up</div>
                </a>
              </li>
              <li>
                <a href="<%= new_user_session_path %>">
                  <div class="label label-secondary">Sign in</div>
                </a>
              </li>
            <%end%>
          </ul>


          <div class="visible-xs">

            <a href="#" class="menu-trigger">
              <i class="entypo-menu"></i>
            </a>

          </div>
        </nav>

      </header>

    </div>

  </div>

</div>