config/routes.rb
Rails.application.routes.draw do

  # Vistas para el divisional

  # get '/altas', to: 'managers#altas', as: 'altas'
  # get '/bajas', to: 'managers#bajas', as: 'bajas'
  get '/dotaciones', to: 'managers#dotaciones', as: 'dotaciones'
  get '/manager', to: 'managers#dotaciones', as: 'manager'
  get '/movimientos', to: 'managers#movimientos', as: 'movimientos'
  get '/formaciones', to: 'managers#formaciones', as: 'formaciones'
  get '/rotaciones', to: 'managers#rotaciones', as: 'rotaciones'
  get '/remuneraciones', to: 'managers#remuneraciones', as: 'remuneraciones'
  get '/vacaciones', to: 'managers#vacaciones', as: 'vacaciones'
  get '/saldo-vacaciones', to: 'managers#saldo', as: 'saldo'
  # get '/personas', to: 'managers#personas', as: 'personas'
  get '/licencias', to: 'managers#licencias', as: 'licencias'
  #post '/entrada', to: 'managers#entrada', as: 'entrada'
  
  devise_scope :user do
    get 'login', to: 'users/sessions#create'
  end
  get '/users/entrada', to: 'managers#entrada', as: 'user_with_params'
  # post '/users/entrada', to: 'managers#entrada', as: 'user_with_params'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'managers#index'

  namespace :admin do
    post ':model_type/upload', to: 'upload#create', as: :upload
    post ':model_type/remove', to: 'upload#remove', as: :remove
    post '/generate', to: 'upload#generate', as: :generate
    get '/ordenar_gerencias', to: 'vacantes#ordenar_gerencias', as: :ordenar_gerencias
    get '/ordenar_divisiones', to: 'vacantes#ordenar_divisiones', as: :ordenar_divisiones
    post '/crear_orden_gerencias', to: 'vacantes#crear_orden_gerencias', as: :crear_orden_gerencias
    post '/crear_orden_divisiones', to: 'vacantes#crear_orden_divisiones', as: :crear_orden_divisiones
    get '/user/:id/log', to: 'users#log', as: :log_user
    resources :formaciones
    resources :licencias
    resources :empleados
    resources :users
    resources :movimientos
    resources :egresos
    resources :posiciones
    resources :retribuciones
    resources :vacaciones
    resources :vacantes
    resources :user_logs

    root "empleados#index", as: :home
  end

  post "update_role" => "roles#update", as: "update_role"
  resources :users do
    get 'resend_invite', to: "users#resend_invite", as: "resend_invite"
  end

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      post 'upload' => 'upload#create'
      get 'remove' => 'upload#remove'
      get 'generate' => 'upload#generate'
      get 'programa-talentos' => 'programa_talentos#index'
      get 'programa-talentos/:id' => 'programa_talentos#show'
      post 'programa-talentos' => 'programa_talentos#create'
      put 'programa-talentos/:id' => 'programa_talentos#update'
      delete 'programa-talentos/:id' => 'programa_talentos#destroy'
      
      resources :vacantes

      get 'dotaciones-data', to: 'data#dotaciones', as: "dotaciones_data"
      # get 'altas-data' => 'data#altas'
      # get 'bajas-data' => 'data#bajas'
      get 'rotaciones-data', to: 'data#rotaciones', as: "rotaciones_data"
      get 'movimientos-data' => 'data#movimientos', as: "movimientos_data"
      get 'formaciones-data' => 'data#formaciones', as: "formaciones_data"
      get 'remuneraciones-data' => 'data#remuneraciones', as: "remuneraciones_data"
      get 'licencias-data' => 'data#licencias', as: "licencias_data"
      get 'vacaciones-data' => 'data#vacaciones', as: "vacaciones_data"
      get 'saldo-data' => 'data#saldo', as: "saldo_data"

      get 'estructura-data' => 'data#estructura', as: "estructura_data"
      get 'estructura_licencias' => 'data#estructura_licencias', as: "estructura_licencias"

      post 'user_logs', to: 'data#user_logs', as: 'user_logs'
      
    end
  end
end

app/models/movimiento.rb
# == Schema Information
#
# Table name: movimientos
#
#  id                 :integer          not null, primary key
#  empleado_id        :integer
#  periodo            :string
#  tipo_movimiento    :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  rut                :string
#  periodo_anualizado :string
#

class Movimiento < ActiveRecord::Base
  belongs_to :empleado
  belongs_to :posicion, class_name: 'Posicion', foreign_key: 'posicion_origen_id'

  
  scope :in_period, ->(period) { where('periodo = ?', period) unless period.blank?}

  PARAMETROS = [:periodo, :tipo_movimiento, :rut]

  scope :with_text, -> (text) {
    queries = PARAMETROS.map do |p|
      "#{p.to_s} ILIKE '%#{text}%'"
    end

    where(queries.join(" OR "))
  }

  def self.csv_import(data, periodo)
    # csv_handler = File.open(data.tempfile)
    row_index = 0
    ruts = []
    movimientos = []
    begin
      CSV.foreach(data.tempfile, encoding: Encoding::UTF_8,headers: true, :col_sep => "\t") do |row, index|
        empleado = Empleado.find_by_rut(row["pos_rut"])
        row_index = row_index+1
        if empleado
            movimiento = empleado.movimientos.new
            movimiento.rut = row["pos_rut"]
            movimiento.tipo_movimiento = row["tipo_cambio_posicion"]
            movimiento.periodo = periodo
            # posicion = Posicion.where(rut: movimiento.rut, periodo: (Date.strptime(movimiento.periodo_anualizado, "%m-%Y")-1.month).strftime("%m-%Y")).first
            movimiento.periodo_anualizado = Date.strptime(row["pos_periodo"], "%Y%m").strftime("%m-%Y")
            posicion = Posicion.where(rut: movimiento.rut, periodo: (Date.strptime(movimiento.periodo_anualizado, "%m-%Y")-1.month).strftime("%m-%Y")).first
            movimiento.posicion = posicion
            movimientos << movimiento
        else
          ruts << row["pos_rut"]
        end
      end
      Movimiento.import movimientos
      return ruts
    rescue Exception => e
      puts e.message
      puts e.backtrace.inspect
      return row_index
    end
  end

  def self.add_origen
    Movimiento.where("periodo in (?)",["09-2017", "10-2017", "11-2017"]).each do |movimiento|
      # puts "ANTIGUO: "+movimiento.posicion.id.to_s if movimiento.posicion
      posicion = Posicion.where(rut: movimiento.rut, periodo: (Date.strptime(movimiento.periodo_anualizado, "%m-%Y")-1.month).strftime("%m-%Y")).first
      # if posicion 
      #   puts "NUEVO: "+posicion.id.to_s
      # else 
      #   puts "MOVIMIENTO SIN POSICION: "
      # end
      movimiento.posicion = posicion
      movimiento.save
    end
  end

end

app/controllers/admin/movimientos_controller.rb
class Admin::MovimientosController < AdminController
  before_action -> { @sidebar_menu_item = :movimientos }

  def index
    if params[:month].present? and params[:year].present?
      periodo = "#{params[:month]}-#{params[:year]}"
    else
      periodo = Date.today.strftime("%m-%Y")
    end

    @movimientos = Movimiento.in_period(periodo)

    if params[:query].present?
      @movimientos = @movimientos.with_text(params[:query])
    end

    @movimientos = @movimientos.paginate(page: params[:page])
  end

  def show
    @movimiento = Movimiento.find(params[:id])
  end

  def new
    @empleado = Empleado.find_by!(rut: params[:rut])
    @movimiento = @empleado.movimientos.build
  end

  def create
    @empleado = Empleado.find_by!(rut: params[:movimiento][:rut])
    @movimiento = @empleado.movimientos.build(movimiento_params)

    if @movimiento.save
      flash[:success] = "Entrada creada exitosamente."

      redirect_to admin_movimientos_path
    else
      flash[:danger] = "Por favor corrija los errores indicados antes de continuar."

      render 'new'
    end
  end

  def edit
    @movimiento = Movimiento.find(params[:id])
  end

  def update
    @movimiento = Movimiento.find(params[:id])

    if @movimiento.update_attributes(movimiento_params)
      flash[:success] = "Entrada actualizada exitosamente."
    else
      flash[:danger] = "Por favor corrija los errores indicados antes de continuar."
    end

    render 'edit'
  end

  def destroy
    Movimiento.find(params[:id]).destroy

    flash[:success] = "Entrada eliminada exitosamente."

    redirect_to admin_movimientos_path
  end

  private

  def movimiento_params
    params.require(:movimiento).permit(:tipo_movimiento, :periodo, :rut, :periodo_anualizado)
  end
end

app/controllers/api/v1/movimientos_controller.rb
class Api::V1::MovimientosController < Api::V1::BaseController
        respond_to :json


  def index
    if ( params[:month] and !(params[:month]).empty? and params[:year] and !(params[:year]).empty? )
      period = params[:month]+"-"+params[:year]
      @movimientos = Movimiento.in_period(period)
    else
      period = Date.today.strftime("%m-%Y")
      @movimientos = Movimiento.in_period(period)
    end
    render json: serialize_models(@movimientos)
  end

  def show
    @movimiento = Movimiento.find(params[:id])
    render json: serialize_model(@movimiento)
  end

  def create
    empleado = Empleado.find_by_rut(params[:data][:attributes][:rut])
    movimiento = empleado.movimientos.new(movimientos_params)
    if movimiento.save
      render json: serialize_model(movimiento), status: 201
    else
      render json: serialized_errors(movimiento), status: 422
    end
  end

  def update
    movimiento = Movimiento.find(params[:id])
    attrs = params[:data][:attributes]
    if movimiento.update_attributes(movimiento_params)
      render json: serialize_model(movimiento), status: 201
    else
      render json: serialized_errors(movimiento), status: 422
    end
  end

  def destroy
    movimiento = Movimiento.find(params[:id])
    movimiento.destroy!
    render json: "", status: 204

  end

  private


    def movimiento_params
      params.require(:data).require(:attributes).permit(:rut, :tipo_movimiento, :resto_año, :anual, :periodo, :empleado_id, :periodo_anualizado)
    end



end

app/views/admin/movimientos/_form.html.erb
<div class="form-group">
  <label for="empleado">Empleado</label>
  <input name="empleado" type="text" value="<%= @movimiento.empleado.nombre.split(" ").first.capitalize %> <%= @movimiento.empleado.apellidos.split(" ").first.capitalize %> (RUT: <%= @movimiento.empleado.rut %>)" class="form-control" readonly>
</div>


<%= f.hidden_field :rut, value:  @movimiento.empleado.rut%>

<%= f.input :tipo_movimiento %>

<%= f.input :periodo %>
<%= f.input :periodo_anualizado %>

<hr/>

<div class="text-center">
  <%= f.button :submit, "Enviar", class: "btn btn-primary" %>
</div>

app/views/admin/movimientos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Gestión de Movimientos</h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for @movimiento, url: admin_movimiento_path(@movimiento), method: :put do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/admin/movimientos/index.html.erb
<% provide(:upload_modal_type, "movimientos") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Gestión de movimientos</h4>
  </div>
  <div class="panel-body">
    <%= render "shared/backend/controls" %>

    <div class="well">
      <div class="row">
        <div class="col-md-6">
          <%= render "shared/backend/date_selector", resource: "movimientos" %>
        </div>
      </div>
    </div>

    <div class="text-center">
      <%= will_paginate @empleados, renderer: BootstrapPagination::Rails %>
    </div>

    <table class="table table-bordered table-hover table-striped">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">Empleado</th>
          <th>Tipo</th>
          <th class="text-center">Periodo</th>
          <th class="text-center">Periodo de Carga</th>
          <th class="text-center"><%= fa_icon("cogs") %></th>
        </tr>
      </thead>
      <tbody>
        <% @movimientos.each do |movimiento| %>
          <tr>
            <td class="text-center"><%= movimiento.id %></td>
            <td class="text-center">
              <%= link_to admin_empleado_path movimiento.empleado do %>
                <%= movimiento.empleado.nombre.split(" ").first.capitalize %> <%= movimiento.empleado.apellidos.split(" ").first.capitalize %>
              <% end %>
            </td>
            <td class="text-center"><%= movimiento.tipo_movimiento %></td>

            <td class="text-center"><%= movimiento.periodo_anualizado %></td>
            <td class="text-center"><%= movimiento.periodo %></td>
            <td class="text-center">
              <div class="dropdown">
                <button class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown"><%= fa_icon("caret-down") %></button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="<%= edit_admin_movimiento_path movimiento %>">Editar</a></li>
                    <li><%= link_to "Eliminar", admin_movimiento_path(movimiento), method: :delete, data: {confirm: "Esta acción es irreversible. ¿Está seguro que desea continuar?"} %></li>
                  </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pull-right"> TOTAL: <%=  number_with_delimiter @movimientos.count.to_s%></div>

    <div class="text-center">
      <%= will_paginate @empleados, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/admin/movimientos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Gestión de Movimientos</h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for @movimiento, url: admin_movimientos_path, method: :post do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>